name: clima
description: A Flutter Weather App.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquetes esenciales para la app de clima
  cupertino_icons: ^1.0.6
  http: ^1.2.0          # Actualizado a la última versión
  geolocator: ^10.1.1   # Última versión estable

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Archivos y recursos
  assets:
    - images/

  # Fuente personalizada Spartan MB
  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
